//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalSystem.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CarRegistration
    {
        public int CarID { get; set; }
        public string CarName { get; set; }
        public string CarMileage { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
